// Package front_service GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package front_service

import "github.com/swaggo/swag"

const docTemplatefront_service = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/member": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "會員"
                ],
                "summary": "創建會員",
                "parameters": [
                    {
                        "description": "json",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "request.CreateMemberRequest": {
            "type": "object",
            "required": [
                "account",
                "name",
                "password"
            ],
            "properties": {
                "account": {
                    "description": "會員帳號",
                    "type": "string"
                },
                "name": {
                    "description": "會員名稱",
                    "type": "string"
                },
                "password": {
                    "description": "會員密碼",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfofront_service holds exported Swagger Info so clients can modify it
var SwaggerInfofront_service = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/front",
	Schemes:          []string{},
	Title:            "gin_deom",
	Description:      "前台api",
	InfoInstanceName: "front_service",
	SwaggerTemplate:  docTemplatefront_service,
}

func init() {
	swag.Register(SwaggerInfofront_service.InstanceName(), SwaggerInfofront_service)
}
